name: Run all flows
on:
  workflow_dispatch:
    inputs:
      prefect-version:
        description: Prefect version for flows
        required: true
        default: '2.*'
        type: string
jobs:
  list-flows:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls flows/*.py | jq -R -s -c 'split("\n")[:-1]')"
  deploy:
    runs-on: ubuntu-latest
    needs: list-flows
    strategy:
      matrix:
        flows: ${{ fromJson(needs.list-flows.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Python dependencies
        run: pip install -U prefect==${{ github.event.inputs.prefect-version }}
      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY}} 
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL}}
      - name: Run all flows
        id: run
        run: python ${{matrix.flows}}
